/* Consolidated navigation keeps legacy page IDs and saved trade records intact. */
let auditReportDays=7;
const auditNavigation={statistics:['dashboard','progress','digest','coach'],context:['overview','premarket'],active:'overview',poolFilter:'all'};
function auditCashSummary(trades){
  const closed=(trades||[]).filter(t=>t.status!=='open'),known=closed.filter(t=>t.pnl_usd!==null&&t.pnl_usd!==undefined&&t.pnl_usd!==''&&Number.isFinite(Number(t.pnl_usd)));
  let total=0,peak=0,drawdown=0;known.slice().sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).forEach(t=>{total+=Number(t.pnl_usd);peak=Math.max(peak,total);drawdown=Math.max(drawdown,peak-total);});
  return {total:known.length?total:null,drawdown:known.length?drawdown:null,known:known.length,count:closed.length,complete:known.length===closed.length};
}
function auditSetReportDays(days){auditReportDays=days;renderDigest();document.querySelectorAll('[data-audit-days]').forEach(button=>button.classList.toggle('active',Number(button.dataset.auditDays)===days));}
function auditRefreshCoach(){
  const recs=document.getElementById('coach-recs'),signature=JSON.stringify((typeof journalLedger!=='undefined'?journalLedger.full:null)||allTrades||[]);if(!recs||recs.dataset.historySignature===signature)return;
  recs.dataset.historySignature=signature;recs.innerHTML='<div class="audit-note">'+(terminalStats(allTrades).valid.length<5?'Для анализа повторяющихся ошибок нужны хотя бы 5 закрытых сделок.':'История изменилась. Обнови рекомендации, чтобы разобрать текущие сделки.')+'</div>';
  document.getElementById('coach-psych-grid')?.replaceChildren();renderBiggestMistake(terminalStats(allTrades).valid);
}
function auditAssistantContext(){
  const page=auditNavigation.active,state=({overview:overviewState,marketintel:marketIntelState,battle:battleState,liquidity:liquidityState,trendline:trendlineState,elliott:elliottState})[page];
  const result=state?.result,record=typeof marketLive!=='undefined'?marketLive.records.get(state?.symbol):null;
  return '\nТекущий инструмент (снимок, не поток): '+JSON.stringify({page,symbol:state?.symbol||null,timeframe:state?.tf||null,capturedAt:new Date().toISOString(),historyReceivedAt:record?.at?new Date(record.at).toISOString():null,source:record?.exchange||null,price:result?.current??record?.data?.ticker?.price??null,state:result?.state??result?.phase??null,entryReady:result?.entryReady??result?.trendlineConfirmed??false,invalidation:result?.invalidation??null})+'. Не выдавай кандидат за торговый сигнал; если контекста недостаточно, укажи чего не хватает.';
}
function auditTabs(page){
  const tabs=document.createElement('nav');tabs.className='audit-tabs';tabs.setAttribute('aria-label','Подразделы');
  const items=auditNavigation.statistics.includes(page)?[['dashboard','Результаты','crystal'],['progress','Разбор сделок','book'],['digest','Отчёты','torch'],['coach','Рекомендации','shield']]:[['overview','Рынок сейчас','crystal'],['premarket','Контекст и события','book']];
  for(const [id,label,item] of items){const button=document.createElement('button');button.type='button';button.dataset.auditPage=id;button.innerHTML=worldProtocolItem(item)+'<span>'+label+'</span>';button.addEventListener('click',()=>showPage(id));tabs.append(button);}
  return tabs;
}
function auditMoneyPanel(page){
  const root=document.getElementById('page-'+page);if(!root)return;
  let host=root.querySelector('.audit-money');if(!host){host=document.createElement('div');host.className='audit-money';root.querySelector('.audit-tabs')?.after(host);}
  const closed=typeof ledgerClosed==='function'?ledgerClosed(allTrades||[]):(allTrades||[]).filter(t=>t.status!=='open');
  const raw=page==='digest'?closed.filter(t=>new Date(t.created_at).getTime()>=Date.now()-auditReportDays*86400000):page==='dashboard'?edgePeriodTrades(closed):page==='progress'&&typeof reviewPeriodTrades==='function'?reviewPeriodTrades(closed):closed;
  const stats=terminalStats(raw),cash=auditCashSummary(stats.valid),fmt=n=>n==null?'—':terminalFormatUsd(n);
  host.innerHTML=[['Денежный P&L',fmt(cash.total),cash.known+'/'+cash.count+' сделок с денежным результатом'],['Результат в R',stats.rCount?edgeFmtR(stats.netR,true):'—',stats.rCount+'/'+stats.valid.length+' сделок с измеримым R'],['Просадка в $',fmt(cash.drawdown==null?null:-cash.drawdown),'От пика закрытого результата выбранного периода']].map(([label,value,copy])=>'<article><span>'+label+'</span><strong>'+value+'</strong><small>'+copy+'</small></article>').join('');
  let note=root.querySelector('.audit-stats-note');if(!note){note=document.createElement('div');note.className='audit-note audit-stats-note';host.after(note);}
  note.textContent='Проценты отдельных позиций не складываются в ROI счёта. R вычисляется по входу, выходу и исходному стопу; сделки без этих цен не подтверждают R-статистику. '+(!cash.complete?'Часть денежного результата неизвестна. ':'')+(stats.rCount<stats.valid.length?'Часть выборки не имеет измеримого R. ':'')+(stats.valid.length<5?'Для устойчивых выводов пока недостаточно сделок.':'');
}
function auditOpenAssistant(){
  const page=document.getElementById('page-aichat');if(!page)return;
  page.classList.add('audit-drawer');page.hidden=false;page.setAttribute('role','dialog');page.setAttribute('aria-label','Помощник по текущему инструменту');document.body.classList.add('audit-chat-open');
  const symbol=({overview:overviewState,marketintel:marketIntelState,battle:battleState,liquidity:liquidityState,trendline:trendlineState,elliott:elliottState})[auditNavigation.active]?.symbol;
  page.querySelector('.audit-chat-context').textContent=(symbol?symbol+'/USDT · ':'')+'Текущий раздел: '+(document.querySelector('.page.active h1')?.textContent||auditNavigation.active)+'. Проверяй время и источник рыночных данных в ответе.';
  page.querySelector('textarea,input')?.focus();
}
function auditCloseAssistant(){document.body.classList.remove('audit-chat-open');document.getElementById('page-aichat')?.setAttribute('hidden','');}
function auditPoolFilter(filter){auditNavigation.poolFilter=filter;document.querySelectorAll('.audit-pool-filters button').forEach(button=>button.classList.toggle('active',button.dataset.filter===filter));renderLiquidityMap();}
function auditPoolDetails(pool){
  let dialog=document.getElementById('audit-pool-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='audit-pool-dialog';dialog.className='audit-pool-dialog';document.body.append(dialog);}
  const date=time=>Number.isFinite(time)?new Date(time).toLocaleString('ru-RU',{timeZone:'UTC'})+' UTC':'Неизвестно';
  dialog.innerHTML='<h3>'+worldProtocolItem(pool.status==='swept'?'torch':'crystal')+' '+escHtml(pool.name)+'</h3><strong>'+miFmtPrice(pool.price)+'</strong><p>'+escHtml('Состояние: '+(pool.status==='swept'?'историческое пересечение уровня':'пересечение после формирования не найдено')+'. Формирование: '+date(pool.formedAt)+'. Касания: '+pool.touches+'. Расстояние: '+pool.distancePct.toFixed(2)+'% · '+pool.distanceAtr.toFixed(2)+' ATR.')+'</p><p>Огоньки — относительная оценка силы и близости ценового уровня. Реальный объём стопов или заявок здесь не измеряется.</p><button type="button">Понятно</button>';
  dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.showModal();
}
function auditInstall(){
  const nav=document.querySelector('.top-nav');if(!nav)return;const admin=document.getElementById('topnav-admin')?.cloneNode(true);
  const button=(id,label,emoji)=>`<button type="button" class="top-nav-link" data-page="${id}" onclick="showPage('${id}',this)"><span class="world-nav-slot" aria-hidden="true"><span class="emoji-glyph">${emoji}</span></span><span class="world-nav-label">${label}</span></button>`;
  nav.innerHTML=button('overview','Обзор','📊')+button('marketintel','Аналитика монет','💎')+button('journal','Журнал','📓')+button('battle','Анализ решений','📈')+button('watchtower','Слежка','🔭')+button('dashboard','Статистика','🔬')+`<details class="top-nav-group"><summary><span class="world-nav-slot" aria-hidden="true"><span class="emoji-glyph">🧰</span></span><span class="world-nav-label">Инструменты ⌄</span></summary><div class="top-nav-menu">${[['liquidity','Карта ликвидности'],['trendline','Трендовая линия'],['elliott','Волны Эллиотта']].map(([id,label])=>`<button type="button" data-page="${id}" onclick="showPage('${id}',this)">${label}</button>`).join('')}</div></details>`;
  for(const page of [...auditNavigation.statistics,...auditNavigation.context])document.getElementById('page-'+page)?.prepend(auditTabs(page));
  const dashboard=document.querySelector('#page-dashboard h1');if(dashboard)dashboard.textContent='СТАТИСТИКА';
  const reports=document.getElementById('page-digest');if(reports){const days=document.createElement('div');days.className='audit-tabs';days.innerHTML=[7,30,90].map(n=>`<button type="button" data-audit-days="${n}" class="${n===7?'active':''}" onclick="auditSetReportDays(${n})">${n} дней</button>`).join('');reports.querySelector('.audit-tabs')?.after(days);}
  const profile=document.querySelector('.jtb-profile-btn');if(profile){const host=document.createElement('div');host.className='audit-profile';profile.before(host);const trigger=document.createElement('button');trigger.type='button';trigger.className='jtb-profile-btn';trigger.innerHTML=profile.innerHTML;trigger.setAttribute('aria-label','Профиль, помощь и настройки');trigger.setAttribute('aria-expanded','false');const menu=document.createElement('div');menu.className='audit-profile-menu';menu.hidden=true;menu.innerHTML='<button type="button" data-page="settings">Настройки</button><button type="button" data-page="library">Книга / справочник</button><button type="button" data-assistant>Помощник</button><a href="profile.html">Мой профиль</a><a href="screener.html" target="_blank" rel="noopener">Скринер ↗</a>';if(admin)menu.append(admin);host.append(trigger,menu);profile.remove();trigger.addEventListener('click',()=>{menu.hidden=!menu.hidden;trigger.setAttribute('aria-expanded',String(!menu.hidden));});menu.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;menu.hidden=true;trigger.setAttribute('aria-expanded','false');if(target.dataset.assistant!==undefined)auditOpenAssistant();else showPage(target.dataset.page);});document.addEventListener('click',event=>{if(!host.contains(event.target)){menu.hidden=true;trigger.setAttribute('aria-expanded','false');}});}
  const chat=document.getElementById('page-aichat');if(chat){chat.hidden=true;const header=document.createElement('div');header.className='audit-drawer-head';header.innerHTML='<strong>Помощник</strong><button type="button" aria-label="Закрыть помощника">×</button><p class="audit-chat-context"></p>';header.querySelector('button').addEventListener('click',auditCloseAssistant);chat.prepend(header);}
  for(const id of ['liquidity','trendline','elliott','marketintel','journal','battle']){const root=document.getElementById('page-'+id),actions=document.createElement('div');actions.className='audit-assist-actions';actions.innerHTML='<button type="button" data-help>'+worldProtocolItem('book')+' Справочник</button><button type="button" data-chat>Помощник</button>';actions.querySelector('[data-help]').addEventListener('click',()=>id==='elliott'?openElliottLibraryTopic():showPage('library'));actions.querySelector('[data-chat]').addEventListener('click',auditOpenAssistant);root?.append(actions);}
  const ladder=document.querySelector('.lq-ladder');if(ladder){const filters=document.createElement('div');filters.className='audit-pool-filters';filters.innerHTML=[['all','Все уровни'],['live','Неснятые'],['near','Ближайшие ≤ 2 ATR']].map(([id,label])=>`<button type="button" data-filter="${id}" class="${id==='all'?'active':''}" onclick="auditPoolFilter('${id}')">${label}</button>`).join('');ladder.querySelector('.lq-card-head')?.after(filters);const note=document.createElement('div');note.className='audit-note';note.textContent='Предполагаемые зоны по экстремумам. Между ступенями показано расстояние в ATR; огоньки — оценка силы, не объём заявок.';ladder.append(note);}
  const drawPools=worldRenderLiquidity;worldRenderLiquidity=function(data,target='lq-chart'){const visible={...data,pools:data.pools.filter(p=>target!=='lq-chart'?true:auditNavigation.poolFilter==='live'?p.status==='live':auditNavigation.poolFilter==='near'?p.status==='live'&&p.distanceAtr<=2:true)};drawPools(visible,target);const rows=[...document.getElementById(target)?.querySelectorAll('.world-pool')||[]];rows.forEach((row,i)=>{const pool=data.pools.find(p=>p.price===Number(row.dataset.price));if(pool){row.addEventListener('dblclick',()=>auditPoolDetails(pool));row.addEventListener('keydown',event=>{if(event.key==='i')auditPoolDetails(pool);});const info=document.createElement('button');info.type='button';info.className='audit-pool-info';info.textContent='i';info.setAttribute('aria-label','Происхождение и состояние '+pool.name);info.addEventListener('click',event=>{event.stopPropagation();auditPoolDetails(pool);});row.append(info);}if(i){const previous=Number(rows[i-1].dataset.price),distance=Math.abs(previous-Number(row.dataset.price))/(data.atr||1);if(distance>.75){const gap=document.createElement('div');gap.className='audit-pool-gap';gap.textContent='↕ '+distance.toFixed(2)+' ATR';row.before(gap);}}});};
  const trendRender=renderTrendlineEngine;renderTrendlineEngine=function(...args){const value=trendRender(...args),result=trendlineState.result;if(result?.found){const note=document.getElementById('tl-plan-note'),age=result.triggerAge==null?'Нет подтверждённого пробоя':('Подтверждение '+result.triggerAge+' закрытых свечей назад');if(note)note.textContent=trendlineStateCopy(result)+' '+age+'. '+(result.plan?.targetSource||'');}return value;};
  const environment=renderEnvironment;renderEnvironment=function(...args){const output=environment(...args),snapshot=environmentState.snapshot;if(!snapshot?.count){for(const id of ['env-market-regime','env-regime-code']){const el=document.getElementById(id);if(el)el.textContent='НЕДОСТАТОЧНО ДАННЫХ';}for(const id of ['env-breadth','env-volatility','env-btc-change']){const el=document.getElementById(id);if(el)el.textContent='—';}}return output;};
  const refreshStats=renderDashboard;renderDashboard=function(...args){const output=refreshStats(...args);auditRefreshCoach();if(['digest','coach'].includes(auditNavigation.active)){if(auditNavigation.active==='digest')renderDigest();auditMoneyPanel(auditNavigation.active);}return output;};
  for(const [name,page] of [['renderEdgeV2','dashboard'],['renderProgress','progress'],['renderDigest','digest']]){const original=window[name];if(original)window[name]=function(...args){const value=original(...args);auditMoneyPanel(page);return value;};}
  const navigate=showPage;showPage=function(page,control){if(page==='aichat'){auditOpenAssistant();return;}auditCloseAssistant();auditNavigation.active=page;navigate(page,control);document.querySelectorAll('[data-audit-page]').forEach(button=>{const active=button.dataset.auditPage===page;button.classList.toggle('active',active);button.setAttribute('aria-current',active?'page':'false');});if(auditNavigation.statistics.includes(page)){const btn=nav.querySelector('[data-page="dashboard"]');btn.classList.add('active');btn.setAttribute('aria-current','page');auditMoneyPanel(page);}if(page==='premarket'){const btn=nav.querySelector('[data-page="overview"]');btn.classList.add('active');btn.setAttribute('aria-current','page');}if(page==='coach')auditRefreshCoach();};
  document.addEventListener('keydown',event=>{if(event.key==='Escape')auditCloseAssistant();});
  const active=document.querySelector('.page.active')?.id.replace('page-','')||'overview';auditNavigation.active=active;nav.querySelector('[data-page="'+active+'"]')?.classList.add('active');document.querySelectorAll('[data-audit-page="'+active+'"]').forEach(button=>button.classList.add('active'));
  renderEnvironment();
  document.querySelector('#page-elliott .el-head p').textContent='Свечи, основной и альтернативный счёт, линии подтверждения и RSI. Неполная история оставляет модель кандидатом.';
  const waveTF=document.querySelector('.el-tfs'),waveHead=document.querySelector('.el-chart-card .el-card-head');if(waveTF&&waveHead)waveHead.append(waveTF);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',auditInstall,{once:true});else auditInstall();
