/* Coin observatory: real OHLC, full-history indicators and aligned price/RSI pivots. */
const coinTfMs={'5m':300000,'15m':900000,'1h':3600000,'4h':14400000,'1d':86400000};
const coinDesk={symbol:'',analysis:null,request:0,loading:false,window:120,shift:0,focus:false,options:{ema21:true,ema50:true,ema200:false,levels:true,volume:true,rsi:true,divergence:true}};
WORLD_PROTOCOL_SPRITES.rocket=['.....mm.....','....mwwm....','...mwcwwm...','...mccwwm...','...mwvvwm...','...mwvvwm...','..mmwwwwmm..','.mmwwwwwwmm.','.mdmmwwmmdm.','...dgoood...','....goog....','.....g......'];
WORLD_PROTOCOL_SPRITES.warning=['.....gg.....','....goog....','...gooog....','...googo....','..gooogoog..','..gooogoog..','.goooogooog.','.goooooooog.','gooooddooogg','goooooooooog','gggggggggggg','............'];
const coinItem=kind=>worldProtocolItem(kind).replace('"></i>','!important"></i>');
function coinDetailPrice(value){return Number.isFinite(value)?'$'+value.toLocaleString('en-US',{maximumSignificantDigits:10}):'—';}
function coinClosedCandles(rows,tf,now=Date.now()){return (rows||[]).filter(c=>c.time+coinTfMs[tf]<=now);}
function coinSeries(rows){const closes=rows.map(c=>c.close);return {ema21:miEMA(closes,21),ema50:miEMA(closes,50),ema200:miEMA(closes,200),rsi:miRSISeries(rows)};}
function coinViewport(rows,count,shift,div,focus){
  let end=Math.max(2,rows.length-Math.max(0,shift)),start=Math.max(0,end-count);
  if(focus&&div?.found){start=Math.max(0,div.first.index-12);end=Math.min(rows.length,Math.max(start+count,div.second.index+16));if(end-start>320)start=Math.max(0,end-320);}
  return {start,end,rows:rows.slice(start,end)};
}
function coinDivergenceVisible(div,start,end){return Boolean(div?.found&&div.first.index>=start&&div.second.index<end&&div.first.index<div.second.index);}
function coinPrepareAnalysis(original){
  const inds={};MI_INTERVALS.forEach(tf=>inds[tf]=miIndicators(coinClosedCandles(marketIntelState.candles[tf],tf)));
  let score=50;[['15m',4],['1h',8],['4h',13],['1d',15]].forEach(([tf,w])=>{const ind=inds[tf];score+=ind.last>ind.ema21?w/2:-w/2;if(ind.rsi>54)score+=w/2;else if(ind.rsi<46)score-=w/2;});
  score+=inds['4h'].macd.hist>0?6:-6;const change=original.ticker.changePct;if(Number.isFinite(change))score+=change>0?Math.min(7,change*1.2):-Math.min(7,Math.abs(change)*1.2);score=Math.round(miClamp(score,0,100));
  const directions=MI_INTERVALS.map(tf=>inds[tf].rsi>=52&&inds[tf].last>=inds[tf].ema21?1:inds[tf].rsi<=48&&inds[tf].last<=inds[tf].ema21?-1:0),bull=directions.filter(n=>n===1).length,bear=directions.filter(n=>n===-1).length;
  const verdict=score>=70?{title:'ПОКУПАТЕЛИ СИЛЬНЕЕ',tone:'good',copy:'Закрытые свечи показывают перевес покупателей. Смотри реакцию у сопротивления и не пропускай риск отката.'}:score>=57?{title:'УМЕРЕННО БЫЧИЙ ФОН',tone:'good',copy:'Перевес покупателей есть, но горизонты ещё не полностью согласованы.'}:score>43?{title:'НАПРАВЛЕНИЯ РАСХОДЯТСЯ',tone:'warn',copy:'Чистого перевеса нет. Следи за границами диапазона и совпадением импульса.'}:score>30?{title:'УМЕРЕННО МЕДВЕЖИЙ ФОН',tone:'bad',copy:'Перевес продавцов есть. Проверь поддержку и восстановление импульса.'}:{title:'ПРОДАВЦЫ СИЛЬНЕЕ',tone:'bad',copy:'Закрытые свечи показывают давление продавцов. Важны реакция на поддержку и признаки ослабления импульса.'};
  return {...original,inds,score,bull,bear,confidence:Math.round(Math.max(bull,bear)/4*100),dailyTrend:miTrend(inds['1d']),verdict};
}
function coinInstall(){
  const section=miEl('market-intel');if(!section||miEl('coin-snapshot'))return;section.classList.add('coin-observatory');
  section.querySelector('.mi-head p').textContent='Вся картина монеты: направление, важные уровни, объём и импульс. Сверь цену и RSI на одном графике.';
  const bar=document.querySelector('.jnl-topbar');if(bar){const resize=()=>document.documentElement.style.setProperty('--coin-nav-offset',(getComputedStyle(bar).position==='fixed'?bar.getBoundingClientRect().height+16:16)+'px');new ResizeObserver(resize).observe(bar);resize();}
  const snapshot=document.createElement('div');snapshot.id='coin-snapshot';snapshot.className='coin-snapshot';snapshot.setAttribute('aria-label','Главные наблюдения по монете');section.querySelector('.mi-hero').before(snapshot);
  const score=section.querySelector('.mi-score-card .mi-card-title');score.textContent='КОМПАС МОНЕТЫ';score.prepend(document.createRange().createContextualFragment(coinItem('rocket')));
  section.querySelector('.mi-score-card .mi-card-sub').textContent='Индекс фона: продавцы 0 → покупатели 100 · не вероятность';
  const meter=document.createElement('div');meter.id='coin-bias-meter';meter.className='pixel-meter-host';section.querySelector('.mi-score-main').after(meter);
  miEl('mi-score-ring').querySelector('small').textContent='ФОН / 100';
  const icons=['torch','rocket','warning','torch','crystal','book'];section.querySelectorAll('.mi-metric').forEach((card,i)=>card.prepend(document.createRange().createContextualFragment(coinItem(icons[i]))));
  const chart=section.querySelector('.mi-chart-card');chart.classList.add('coin-chart-card');chart.querySelector('.mi-card-title').textContent='СВЕЧИ И ИНДИКАТОРЫ';chart.querySelector('.mi-card-title').prepend(document.createRange().createContextualFragment(coinItem('crystal')));
  const tools=document.createElement('div');tools.className='coin-chart-tools';tools.innerHTML='<div class="coin-overlay-tools" aria-label="Слои графика">'+[['ema21','EMA 21'],['ema50','EMA 50'],['ema200','EMA 200'],['levels','Уровни 4ч'],['volume','Объём'],['rsi','RSI 14'],['divergence','Дивергенции']].map(([key,title])=>'<button type="button" data-coin-overlay="'+key+'" aria-pressed="'+coinDesk.options[key]+'" onclick="coinToggle(\''+key+'\')">'+title+'</button>').join('')+'</div><div class="coin-window-tools" aria-label="История графика">'+[60,120,240].map(n=>'<button type="button" data-coin-window="'+n+'" aria-pressed="'+(n===120)+'" onclick="coinWindow('+n+')">'+n+' свечей</button>').join('')+'<button type="button" id="coin-earlier" onclick="coinPan(1)" aria-label="Предыдущая часть истории">←</button><button type="button" id="coin-later" onclick="coinPan(-1)" aria-label="Следующая часть истории">→</button><button type="button" onclick="coinCurrent()">К текущей цене</button></div>';chart.querySelector('.mi-card-head').after(tools);
  const wrap=miEl('mi-chart-wrap');wrap.querySelector('.mi-chart-legend').remove();const legend=document.createElement('div');legend.id='coin-chart-legend';legend.className='coin-chart-legend';wrap.before(legend);
  const divInfo=document.createElement('div');divInfo.id='coin-chart-divergence';divInfo.className='coin-chart-divergence';wrap.after(divInfo);
  const tip=miEl('world-mi-tooltip');if(tip){chart.querySelector('.mi-chart-foot').after(tip);tip.hidden=false;tip.classList.add('coin-readout');tip.textContent='Наведи на свечу или выбери её стрелками ← →. Цена, объём, EMA и RSI связаны по времени.';}
  miEl('mi-chart').setAttribute('aria-label','Свечи, EMA, объём и RSI. Стрелки выбирают свечу, Escape убирает курсор.');
  section.querySelector('.mi-rsi-lab .mi-card-title').prepend(document.createRange().createContextualFragment(coinItem('torch')));
  section.querySelector('.mi-rsi-lab .mi-card-sub').textContent='RSI 14 · закрытые свечи · нажми горизонт для графика';
  section.querySelectorAll('[data-mi-rsi]').forEach(card=>{card.tabIndex=0;card.setAttribute('role','button');const choose=()=>setMarketChartTF(card.dataset.miRsi);card.addEventListener('click',choose);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});const mini=document.createElement('div');mini.className='coin-rsi-mini';card.append(mini);});
  [['.mi-divergence','crystal'],['.mi-structure','hammer'],['.mi-signals','warning'],['.mi-scenario','flag']].forEach(([cls,item])=>section.querySelector(cls+' .mi-card-title').prepend(document.createRange().createContextualFragment(coinItem(item))));
  const actions=document.createElement('div');actions.className='coin-actions';actions.innerHTML='<button type="button" onclick="coinOpen(\'liquidity\')">'+coinItem('crystal')+'Карта ликвидности →</button><button type="button" onclick="coinOpen(\'battle\')">'+coinItem('shield')+'Проверить сценарий →</button>';section.querySelector('.mi-scenario').append(actions);
  section.querySelectorAll('.mi-levels>div').forEach((cell,i)=>cell.prepend(document.createRange().createContextualFragment(coinItem(i?'crystal':'shield'))));
}
function coinRenderSummary(a){
  coinInstall();coinDesk.analysis=a;coinDesk.symbol=marketIntelState.symbol;const trend=a.dailyTrend,vol=a.inds['1h'].volumeRatio,rsi=a.inds['4h'].rsi,divs=Object.values(a.divergences).filter(d=>d.found),opposite=divs.find(d=>(a.score>=57&&d.direction==='bear')||(a.score<=43&&d.direction==='bull'));
  const warning=opposite?opposite.title+' дивергенция · '+MI_TF_LABELS[opposite.tf]:rsi>=70?'RSI 4ч перегрет':rsi<=30?'RSI 4ч в перепроданности':Number.isFinite(vol)&&vol<.7?'Объём 1ч ниже обычного':'Проверь реакцию у уровня';
  const warningCopy=opposite?'Импульс расходится с основным фоном. Открой отмеченные опоры.':rsi>=70?'Сильный рост не отменяет риска отката.':rsi<=30?'Давление продавцов сильное; возможен отскок.':vol<.7?'Последняя закрытая свеча, а не незавершённый бар.':'Перевес фона ещё не подтверждает вход.';
  const target=a.score>56?a.levels.resistance:a.score<44?a.levels.support:null;
  miEl('coin-snapshot').innerHTML=[['rocket','НАПРАВЛЕНИЕ',trend.label,trend.copy,trend.tone],['crystal','БЛИЖАЙШАЯ ПРОВЕРКА',target?miFmtPrice(target):'Границы диапазона',target?(a.score>56?'Сопротивление':'Поддержка')+' 4ч · '+miPct((target/a.current-1)*100):miFmtPrice(a.levels.support)+' — '+miFmtPrice(a.levels.resistance),'context'],['warning','ЧТО УЧЕСТЬ',warning,warningCopy,'warning']].map(([item,label,value,copy,state])=>'<article class="coin-snapshot-tile '+state+'">'+coinItem(item)+'<div><span>'+label+'</span><strong>'+escHtml(value)+'</strong><small>'+escHtml(copy)+'</small></div></article>').join('');
  pixelSetMeter('coin-bias-meter',a.score,{label:'Индекс фона от продавцов к покупателям',max:100,segments:20,caption:'Закрытые свечи 15м–1д · индекс не является вероятностью сделки'});
  miSet('mi-page-title',marketIntelState.symbol+' / АНАЛИТИКА МОНЕТ');miSet('mi-asset-symbol',(MARKET_COIN_NAMES[marketIntelState.symbol]||marketIntelState.symbol)+' · '+marketIntelState.symbol+' / USDT');miSet('mi-metric-vol-note','Закрытая свеча 1ч · к среднему');
  if(window.etMarketFeed?.fng==null){miSet('mi-metric-fng','—');miSet('mi-metric-fng-note','Индекс недоступен');miToneClass(miEl('mi-metric-fng'),'');}
  if(!divs.length)miEl('mi-div-summary').querySelector('b').textContent='НЕТ РАСХОЖДЕНИЙ';
  MI_INTERVALS.forEach(tf=>{const card=document.querySelector('[data-mi-rsi="'+tf+'"]'),value=a.inds[tf].rsi;card.setAttribute('aria-label',MI_TF_LABELS[tf]+', RSI '+(Number.isFinite(value)?value.toFixed(1):'нет данных')+'. Открыть график');card.setAttribute('aria-pressed',String(marketIntelState.chartTF===tf));const host=card.querySelector('.coin-rsi-mini'),series=miRSISeries(coinClosedCandles(marketIntelState.candles[tf],tf)).slice(-18);host.innerHTML=series.map(n=>'<i style="--rsi-height:'+(Number.isFinite(n)?Math.max(3,n):3)+'%" class="'+(n>=70?'hot':n<=30?'cold':'')+'"></i>').join('');});
  document.querySelectorAll('.mi-structure-row').forEach((row,i)=>row.querySelector('span')?.prepend(document.createRange().createContextualFragment(coinItem(['torch','crystal','rocket','warning','hammer','flag'][i]||'book'))));
  document.querySelectorAll('.mi-signal').forEach(row=>{row.querySelector('i')?.remove();row.prepend(document.createRange().createContextualFragment(coinItem(row.classList.contains('bad')||row.classList.contains('warn')?'warning':'torch')));});
  document.querySelectorAll('[data-mi-div-tf]').forEach(card=>{const div=a.divergences[card.dataset.miDivTf];card.classList.toggle('coin-div-found',Boolean(div?.found));const first=card.querySelector('.mi-div-tf');first.querySelector('.tl-inventory-item')?.remove();first.prepend(document.createRange().createContextualFragment(coinItem(div?.found?'crystal':'book')));if(!div?.found)card.querySelector('.mi-div-status').textContent='НЕТ РАСХОЖДЕНИЯ';card.setAttribute('aria-label',MI_TF_LABELS[card.dataset.miDivTf]+': '+(div?.found?div.kind:'Подтверждённого расхождения нет')+'. Открыть цену и RSI');});
  coinUpdateFreshness();worldFitPanels(miEl('page-marketintel'));
}
function coinUpdateFreshness(){
  if(!coinDesk.analysis||coinDesk.loading)return;const age=Math.max(0,Math.round((Date.now()-marketIntelState.loadedAt)/1000));miSet('mi-data-age',age>120?'ДАННЫЕ УСТАРЕЛИ · '+age+'с':age+'с назад · котировки');miEl('market-intel').classList.toggle('coin-stale',age>120);
}
function coinScrollTop(){window.scrollTo({top:0,behavior:'instant'});document.body.scrollTo({top:0,behavior:'instant'});document.querySelector('.main')?.scrollTo({top:0,behavior:'instant'});}
function coinOpen(page){
  const symbol=marketIntelState.symbol;
  if(page==='liquidity'){liquidityState.symbol=symbol;showPage(page,document.querySelector('[data-page="'+page+'"]'));liquidityScan(symbol,false);}
  else if(page==='battle'){battleState.symbol=symbol;showPage(page,document.querySelector('[data-page="'+page+'"]'));battleScan(symbol);}
}
function coinToggle(key){if(!(key in coinDesk.options))return;coinDesk.options[key]=!coinDesk.options[key];document.querySelector('[data-coin-overlay="'+key+'"]').setAttribute('aria-pressed',String(coinDesk.options[key]));if(coinDesk.analysis)worldRenderMarketInstrument(coinDesk.analysis);}
function coinWindow(count){coinDesk.window=count;coinDesk.focus=false;document.querySelectorAll('[data-coin-window]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.coinWindow)===count)));if(coinDesk.analysis)worldRenderMarketInstrument(coinDesk.analysis);}
function coinPan(direction){const total=marketIntelState.candles[marketIntelState.chartTF]?.length||0;coinDesk.shift=miClamp(coinDesk.shift+direction*Math.round(coinDesk.window*.6),0,Math.max(0,total-coinDesk.window));coinDesk.focus=false;if(coinDesk.analysis)worldRenderMarketInstrument(coinDesk.analysis);}
function coinCurrent(){coinDesk.shift=0;coinDesk.focus=false;if(coinDesk.analysis)worldRenderMarketInstrument(coinDesk.analysis);}
function coinChartRender(a){
  const svg=miEl('mi-chart'),tf=marketIntelState.chartTF,full=marketIntelState.candles[tf]||[],div=a.divergences[tf],view=coinViewport(full,coinDesk.window,coinDesk.shift,div,coinDesk.focus),rows=view.rows;
  if(!svg||rows.length<2){if(svg)svg.replaceChildren();worldInstrument=null;return;}
  const series=coinSeries(full),sliced=Object.fromEntries(Object.entries(series).map(([k,v])=>[k,v.slice(view.start,view.end)])),o=coinDesk.options;
  const width=svg.clientWidth||900,height=svg.clientHeight||570,left=width<500?8:14,right=width-(width<500?65:86),top=25,axis=height-24,rsiHeight=o.rsi?112:0,volumeHeight=o.volume?62:0,bottom=axis-rsiHeight-volumeHeight-(o.rsi?20:0)-(o.volume?18:0),volumeTop=bottom+18,volumeBottom=volumeTop+volumeHeight,rsiTop=axis-rsiHeight,rsiBottom=axis;
  const dark=worldTheme()==='dark',up=dark?'#54d1d5':'#158db0',down=dark?'#ae88ed':'#9260d7',gold=dark?'#e5c87e':'#967326',caption=dark?'#a6b2d0':'#58667e',edge=dark?'#354365':'#cbd6e9';
  const colors={ema21:up,ema50:down,ema200:gold},values=rows.flatMap(c=>[c.low,c.high]);for(const key of ['ema21','ema50','ema200'])if(o[key])values.push(...sliced[key].filter(Number.isFinite));if(o.levels)values.push(a.levels.support,a.levels.resistance);
  const min=Math.min(...values),max=Math.max(...values),padding=(max-min||max*.01)*.1,span=max-min+padding*2,x=i=>left+(i+.5)/rows.length*(right-left),y=p=>top+(max+padding-p)/span*(bottom-top),rsiY=n=>rsiBottom-n/100*rsiHeight;
  const path=(list,map)=>{let started=false;return list.map((v,i)=>{if(!Number.isFinite(v)){started=false;return '';}const cmd=started?'L':'M';started=true;return cmd+x(i).toFixed(2)+' '+map(v).toFixed(2);}).join(' ');};
  svg.setAttribute('viewBox','0 0 '+width+' '+height);svg.setAttribute('preserveAspectRatio','xMidYMid meet');let draw='';
  for(let n=0;n<5;n++){const price=max+padding-n/4*span,yy=y(price);draw+='<path d="M'+left+' '+yy+'H'+right+'" stroke="'+edge+'" stroke-dasharray="2 6"/><text x="'+(right+7)+'" y="'+(yy+4)+'" fill="'+caption+'" font-size="10">'+escHtml(miFmtPrice(price))+'</text>';}
  const body=Math.max(1,Math.min(9,(right-left)/rows.length*.64)),maxVolume=Math.max(...rows.map(c=>c.volume),1);
  rows.forEach((c,i)=>{const color=c.close>=c.open?up:down,xx=x(i);draw+='<g class="coin-candle" data-index="'+(view.start+i)+'"><path d="M'+xx+' '+y(c.high)+'V'+y(c.low)+'" stroke="'+color+'"/><rect x="'+(xx-body/2)+'" y="'+Math.min(y(c.open),y(c.close))+'" width="'+body+'" height="'+Math.max(1,Math.abs(y(c.open)-y(c.close)))+'" fill="'+color+'"/></g>';if(o.volume){const h=c.volume/maxVolume*(volumeHeight-14);draw+='<rect class="coin-volume-bar" x="'+(xx-body/2)+'" y="'+(volumeBottom-h)+'" width="'+body+'" height="'+h+'" fill="'+color+'" opacity=".55"/>';}});
  for(const key of ['ema21','ema50','ema200'])if(o[key])draw+='<path class="coin-ema '+key+'" d="'+path(sliced[key],y)+'" fill="none" stroke="'+colors[key]+'" stroke-width="1.7"'+(key==='ema200'?' stroke-dasharray="4 3"':'')+'/>';
  if(o.levels)[[a.levels.support,up,'S'],[a.levels.resistance,down,'R']].forEach(([p,color,label])=>{const yy=y(p);draw+='<path class="coin-level-line" d="M'+left+' '+yy+'H'+right+'" stroke="'+color+'" stroke-dasharray="5 5" opacity=".65"/><rect x="'+(left+4)+'" y="'+(yy-19)+'" width="22" height="17" fill="var(--world-inset)" stroke="'+color+'"/><text x="'+(left+15)+'" y="'+(yy-7)+'" fill="'+color+'" text-anchor="middle" font-size="10">'+label+'</text>';});
  if(o.volume)draw+='<text x="'+left+'" y="'+(volumeTop+10)+'" fill="'+caption+'" font-size="10">ОБЪЁМ · '+escHtml(marketIntelState.symbol)+'</text>';
  if(o.rsi){draw+='<rect x="'+left+'" y="'+rsiTop+'" width="'+(right-left)+'" height="'+(rsiHeight*.3)+'" fill="'+down+'" opacity=".08"/><rect x="'+left+'" y="'+rsiY(30)+'" width="'+(right-left)+'" height="'+(rsiHeight*.3)+'" fill="'+up+'" opacity=".08"/>';for(const n of [30,50,70])draw+='<path d="M'+left+' '+rsiY(n)+'H'+right+'" stroke="'+edge+'" stroke-dasharray="3 4"/><text x="'+(right+7)+'" y="'+(rsiY(n)+4)+'" fill="'+caption+'" font-size="10">'+n+'</text>';draw+='<text x="'+left+'" y="'+(rsiTop+11)+'" fill="'+caption+'" font-size="10">RSI 14</text><path class="coin-rsi-path" d="'+path(sliced.rsi,rsiY)+'" fill="none" stroke="'+gold+'" stroke-width="1.8"/>';}
  const visible=coinDivergenceVisible(div,view.start,view.end);
  if(o.divergence&&visible){const color=div.direction==='bull'?up:down,first=div.first.index-view.start,second=div.second.index-view.start;for(const [lane,map,key] of [['price',y,'price'],...(o.rsi?[['rsi',rsiY,'rsi']]:[])]){draw+='<path class="coin-div-line '+lane+'" d="M'+x(first)+' '+map(div.first[key])+'L'+x(second)+' '+map(div.second[key])+'" stroke="'+color+'" stroke-width="3" fill="none" stroke-dasharray="6 3"/>';[div.first,div.second].forEach((p,n)=>{draw+='<rect class="coin-div-point '+lane+'" x="'+(x(p.index-view.start)-4)+'" y="'+(map(p[key])-4)+'" width="8" height="8" fill="var(--world-inset)" stroke="'+color+'" stroke-width="2"/><text x="'+x(p.index-view.start)+'" y="'+(lane==='rsi'?Math.max(rsiTop+14,Math.min(rsiBottom-8,map(p[key])-10)):map(p[key])+(div.direction==='bull'?16:-10))+'" fill="'+color+'" font-size="10" text-anchor="middle">'+(n+1)+'</text>';});}}
  const last=rows.at(-1),lastY=y(last.close);draw+='<rect x="'+(x(rows.length-1)-3)+'" y="'+(lastY-3)+'" width="6" height="6" fill="'+up+'"/>';
  for(let n=0;n<(width<500?2:3);n++){const index=Math.round(n/(width<500?1:2)*(rows.length-1)),label=new Date(rows[index].time).toLocaleString('ru-RU',{timeZone:'UTC',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});draw+='<text x="'+x(index)+'" y="'+(height-7)+'" fill="'+caption+'" font-size="9" text-anchor="'+(n===0?'start':n===(width<500?1:2)?'end':'middle')+'">'+escHtml(label)+'</text>';}
  svg.innerHTML=draw;worldInstrument={analysis:a,candles:rows,ema:sliced.ema21,series:sliced,left,right,x,y,top,bottom,rsiTop,rsiBottom,rsiY,volumeBottom,cursor:-1,cyan:up,start:view.start,end:view.end,tf};worldInspectMarketChart(-1);
  const forming=full.at(-1).time+coinTfMs[tf]>Date.now();miSet('mi-chart-caption',marketIntelState.symbol+'/USDT · '+MI_TF_LABELS[tf]+' · '+rows.length+' свечей · UTC'+(forming&&view.end===full.length?' · последняя формируется':''));miSet('mi-chart-low','МИН '+miFmtPrice(Math.min(...rows.map(c=>c.low))));miSet('mi-chart-current','ЗАКРЫТИЕ '+miFmtPrice(last.close));miSet('mi-chart-high','МАКС '+miFmtPrice(Math.max(...rows.map(c=>c.high))));
  miEl('coin-chart-legend').innerHTML=['<span><i style="background:'+up+'"></i>Рост</span>','<span><i style="background:'+down+'"></i>Снижение</span>',...['ema21','ema50','ema200'].filter(k=>o[k]).map(k=>'<span><i style="background:'+colors[k]+'"></i>'+k.replace('ema','EMA ')+'</span>'),...(o.levels?['<span>S / R · уровни 4ч</span>']:[])].join('');
  miEl('coin-earlier').disabled=view.start===0;miEl('coin-later').disabled=view.end===full.length;
  const info=miEl('coin-chart-divergence');info.classList.toggle('active',Boolean(div?.found));info.innerHTML=coinItem(div?.found?'crystal':'book')+'<div><strong>'+escHtml(div?.found?div.title+' · '+(div.type.startsWith('hidden')?'скрытая':'обычная')+' дивергенция':MI_DIVERGENCE_INTERVALS.includes(tf)?'Подтверждённых дивергенций на '+MI_TF_LABELS[tf]+' нет':'Автопоиск дивергенций: 5м, 15м и 1ч')+'</strong><small>'+escHtml(div?.found?div.kind+' · опоры 1 и 2 связаны на цене и RSI'+(!o.rsi?' · включи RSI для второй линии':''): 'Сравни импульс с ценой. Отсутствие расхождения не подтверждает сделку.')+'</small></div>'+(div?.found&&!visible?'<button type="button" onclick="coinFocusDivergence()">Показать обе опоры →</button>':'');
}
function coinInspect(index){
  const svg=miEl('mi-chart'),tip=miEl('world-mi-tooltip');if(!svg||!tip)return;svg.querySelector('.world-instrument-cursor')?.remove();tip.hidden=false;
  if(!worldInstrument||index<0){if(worldInstrument)worldInstrument.cursor=-1;tip.textContent='Наведи на свечу или выбери её стрелками ← →. Цена, объём, EMA и RSI связаны по времени.';return;}
  const s=worldInstrument,c=s.candles[index];if(!c)return;s.cursor=index;const ns='http://www.w3.org/2000/svg',group=document.createElementNS(ns,'g');group.classList.add('world-instrument-cursor');
  const line=document.createElementNS(ns,'path');line.setAttribute('d','M'+s.x(index)+' '+s.top+'V'+(coinDesk.options.rsi?s.rsiBottom:coinDesk.options.volume?s.volumeBottom:s.bottom));line.setAttribute('stroke',s.cyan);line.setAttribute('stroke-dasharray','2 4');group.append(line);
  const points=[[s.y(c.close),s.cyan]];if(coinDesk.options.rsi&&Number.isFinite(s.series.rsi[index]))points.push([s.rsiY(s.series.rsi[index]),'var(--world-gold)']);points.forEach(([yy,color])=>{const rect=document.createElementNS(ns,'rect');Object.entries({x:s.x(index)-3,y:yy-3,width:6,height:6,fill:color}).forEach(([k,v])=>rect.setAttribute(k,v));group.append(rect);});svg.append(group);
  const indicators=['ema21','ema50','ema200','rsi'].filter(k=>Number.isFinite(s.series[k][index])).map(k=>k==='rsi'?'RSI 14 '+s.series[k][index].toFixed(1):k.replace('ema','EMA ')+' '+coinDetailPrice(s.series[k][index]));
  tip.textContent=new Date(c.time).toLocaleString('ru-RU',{timeZone:'UTC',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+' UTC · O '+coinDetailPrice(c.open)+' · H '+coinDetailPrice(c.high)+' · L '+coinDetailPrice(c.low)+' · C '+coinDetailPrice(c.close)+' · V '+c.volume.toLocaleString('ru-RU',{maximumSignificantDigits:7})+' '+marketIntelState.symbol+' · '+indicators.join(' · ')+(c.time+coinTfMs[s.tf]>Date.now()?' · свеча формируется':' · свеча закрыта');
}
function coinFocusDivergence(){coinDesk.focus=true;coinDesk.options.divergence=true;coinDesk.options.rsi=true;for(const key of ['divergence','rsi'])document.querySelector('[data-coin-overlay="'+key+'"]').setAttribute('aria-pressed','true');if(coinDesk.analysis)worldRenderMarketInstrument(coinDesk.analysis);}
function coinClear(symbol,copy,error=false){
  coinInstall();coinDesk.analysis=null;worldInstrument=null;miEl('market-intel').classList.remove('coin-stale');miSet('mi-page-title',symbol+' / АНАЛИТИКА МОНЕТ');miSet('mi-asset-symbol',symbol+' / USDT');miSet('mi-verdict',error?'НЕТ ДАННЫХ':'ЗАГРУЗКА');miSet('mi-verdict-copy',copy);
  for(const id of ['mi-price','mi-change','mi-low','mi-high','mi-volume','mi-range-pct','mi-trades-count','mi-score','mi-confidence','mi-metric-rsi','mi-metric-trend','mi-metric-atr','mi-metric-vol','mi-metric-dom','mi-metric-fng','mi-support','mi-resistance','mi-range-pos']){miSet(id,'—');miToneClass(miEl(id),'');}
  for(const id of ['coin-snapshot','mi-chart','coin-chart-legend','coin-chart-divergence','mi-structure-list','mi-signal-list'])miEl(id)?.replaceChildren();
  for(const id of ['mi-chart-caption','mi-chart-low','mi-chart-current','mi-chart-high','mi-metric-rsi-note','mi-metric-trend-note','mi-metric-vol-note','mi-metric-fng-note','mi-rsi-sync','mi-div-summary','mi-scenario-copy'])miSet(id,copy);
  miSet('mi-scenario-title',error?'РЫНОК НЕДОСТУПЕН':'ПОЛУЧАЕМ СВЕЧИ');miSet('mi-source',error?'ИСТОЧНИК НЕДОСТУПЕН':'ОЖИДАНИЕ');miSet('mi-data-age',error?'ОШИБКА ЗАГРУЗКИ':'ОЖИДАНИЕ ДАННЫХ');
  document.querySelectorAll('.mi-rsi-card').forEach(card=>{card.querySelector('.mi-rsi-value').textContent='—';card.querySelector('.mi-rsi-zone').textContent=copy;card.querySelector('.coin-rsi-mini').replaceChildren();});
  document.querySelectorAll('.mi-div-card').forEach(card=>{card.classList.remove('good','bad','warn','coin-div-found');card.querySelector('.mi-div-status').textContent='—';card.querySelector('.mi-div-age').textContent='НЕТ ДАННЫХ';card.querySelector('.mi-div-kind').textContent=copy;card.setAttribute('aria-label',MI_TF_LABELS[card.dataset.miDivTf]+': нет данных');card.querySelectorAll('.mi-div-data strong').forEach(n=>n.textContent='—');});
  pixelSetMeter('coin-bias-meter',null,{label:'Нет данных',segments:20});worldInspectMarketChart(-1);
}
async function coinScan(raw,button,force=false){
  const symbol=miCleanSymbol(raw);if(!symbol)return;
  if(coinDesk.loading&&symbol===marketIntelState.symbol&&!force)return;
  if(!force&&!marketIntelState.loading&&symbol===marketIntelState.symbol&&marketIntelState.source!=='РЕЗЕРВНЫЙ ПОТОК'&&marketIntelState.ticker&&Date.now()-marketIntelState.loadedAt<45000&&MI_DATA_INTERVALS.every(tf=>marketIntelState.candles[tf]?.length>=40)){miRenderAnalysis(miBuildAnalysis());return;}
  const request=++coinDesk.request,shared=++marketIntelState.requestId;coinDesk.loading=true;marketIntelState.loading=true;marketIntelState.symbol=symbol;
  if(coinDesk.symbol!==symbol){coinDesk.shift=0;coinDesk.focus=false;}miEl('mi-symbol-input').value=symbol;document.querySelectorAll('[data-mi-symbol]').forEach(b=>b.classList.toggle('active',b.dataset.miSymbol===symbol));coinClear(symbol,'Получаем настоящие свечи 5м–1д…');miEl('mi-loading').classList.add('show');miSet('mi-loading-copy','Загружаем '+symbol+'/USDT · свечи, EMA, объём и RSI');
  try{const data=await miLoadSpotHistory(symbol);if(request!==coinDesk.request||shared!==marketIntelState.requestId)return;if(MI_DATA_INTERVALS.some(tf=>!data.candles[tf]?.every(trendlineValidCandle)||data.candles[tf].length<40))throw Error('Недостаточно достоверных свечей');marketIntelState.candles=data.candles;marketIntelState.ticker=data.ticker;marketIntelState.source=data.source;marketIntelState.loadedAt=Date.now();marketIntelState.loading=false;coinDesk.loading=false;miRenderAnalysis(miBuildAnalysis());}
  catch(error){if(request!==coinDesk.request||shared!==marketIntelState.requestId)return;marketIntelState.ticker=null;marketIntelState.candles=Object.fromEntries(MI_DATA_INTERVALS.map(tf=>[tf,[]]));marketIntelState.loadedAt=0;coinClear(symbol,'Данные '+symbol+' недоступны. Проверь тикер и нажми «Обновить».',true);}
  finally{if(request===coinDesk.request){coinDesk.loading=false;if(shared===marketIntelState.requestId)marketIntelState.loading=false;miEl('mi-loading').classList.remove('show');}}
}
document.addEventListener('DOMContentLoaded',()=>{
  coinInstall();worldRenderMarketInstrument=coinChartRender;worldInspectMarketChart=coinInspect;
  const render=miRenderAnalysis;miRenderAnalysis=function(a){if(marketIntelState.loading){coinClear(marketIntelState.symbol,'Получаем свечи выбранной монеты…');return;}if(!marketIntelState.ticker||marketIntelState.source==='РЕЗЕРВНЫЙ ПОТОК'||MI_DATA_INTERVALS.some(tf=>!marketIntelState.candles[tf]||marketIntelState.candles[tf].length<40)){coinClear(marketIntelState.symbol,'Нет достоверных свечей. Обнови монету.',true);return;}if(coinDesk.symbol!==marketIntelState.symbol){coinDesk.shift=0;coinDesk.focus=false;}const prepared=coinPrepareAnalysis(a);render(prepared);coinRenderSummary(prepared);};
  const select=selectMarketCoin;selectMarketCoin=function(raw,button,force=false){return miEl('page-marketintel').classList.contains('active')?coinScan(raw,button,force):select(raw,button,force);};
  setMarketChartTF=function(tf){if(!(tf in coinTfMs))return;marketIntelState.chartTF=tf;coinDesk.shift=0;coinDesk.focus=false;document.querySelectorAll('[data-mi-chart-tf]').forEach(b=>b.classList.toggle('active',b.dataset.miChartTf===tf));document.querySelectorAll('[data-mi-rsi]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.miRsi===tf)));if(coinDesk.analysis)worldRenderMarketInstrument(coinDesk.analysis);};
  focusMarketDivergence=function(tf){setMarketChartTF(tf);coinFocusDivergence();miEl('mi-chart-wrap').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});};
  const init=initMarketIntel;initMarketIntel=function(){coinInstall();coinScrollTop();init();if(!marketIntelState.loading&&(!marketIntelState.ticker||marketIntelState.source==='РЕЗЕРВНЫЙ ПОТОК'))coinScan(marketIntelState.symbol,null,true);};
  setInterval(coinUpdateFreshness,15000);
});
