import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../journal.html',import.meta.url),'utf8');
const source=readFileSync(new URL('../js/journal-coins.js',import.meta.url),'utf8');
function context(){const ctx=vm.createContext({Date,WORLD_PROTOCOL_SPRITES:{},worldProtocolItem(){},document:{addEventListener(){}},MI_INTERVALS:['15m','1h','4h','1d'],MI_DIVERGENCE_INTERVALS:['5m','15m','1h'],miClamp:(v,a,b)=>Math.max(a,Math.min(b,v)),miAverage:v=>v.filter(Number.isFinite).reduce((a,b)=>a+b,0)/v.filter(Number.isFinite).length});vm.runInContext(html.slice(html.indexOf('function miEMA('),html.indexOf('function miRenderChart(')),ctx);vm.runInContext(source,ctx);return ctx;}
const candle=(i,p=100+i/10,tf=300000)=>({time:1700000000000+i*tf,open:p-.1,high:p+.5,low:p-.5,close:p,volume:100});
test('EMA and RSI retain full-history values when the display window changes',()=>{const ctx=context(),rows=Array.from({length:300},(_,i)=>candle(i,100+Math.sin(i/7)*8+i/9)),s=ctx.coinSeries(rows);assert.equal(s.ema200[198],null);assert.ok(Number.isFinite(s.ema200[299]));for(const count of [60,120,240]){const view=ctx.coinViewport(rows,count,0,null,false);assert.equal(view.rows.at(-1),rows.at(-1));assert.equal(s.ema200.slice(view.start,view.end).at(-1),ctx.miEMA(rows.map(c=>c.close),200).at(-1));assert.equal(s.rsi.slice(view.start,view.end).at(-1),ctx.miRSI(rows));}});
test('a candle is closed at its exact interval boundary, including the last returned bar',()=>{const ctx=context(),now=1800000000000,rows=[{time:now-600000},{time:now-300000},{time:now-299999}];assert.equal(ctx.coinClosedCandles(rows,'5m',now).length,2);assert.equal(ctx.coinClosedCandles(rows,'5m',now-1).length,1);});
test('history focus contains both actual divergence pivots without changing their indices',()=>{const ctx=context(),rows=Array.from({length:200},(_,i)=>candle(i)),div={found:true,first:{index:70},second:{index:150}};let view=ctx.coinViewport(rows,120,0,div,false);assert.equal(ctx.coinDivergenceVisible(div,view.start,view.end),false);view=ctx.coinViewport(rows,120,0,div,true);assert.equal(ctx.coinDivergenceVisible(div,view.start,view.end),true);assert.equal(view.rows[70-view.start],rows[70]);assert.equal(view.rows[150-view.start],rows[150]);assert.ok(view.start>=0&&view.end<=rows.length);});
test('closed-bar volume and momentum ignore a forming candle spike',()=>{const ctx=context(),now=Date.now(),rows=Array.from({length:240},(_,i)=>({...candle(i,100+Math.sin(i/4)*5),time:now-(241-i)*3600000}));rows.push({time:now,open:100,high:1000,low:50,close:999,volume:1000000});ctx.marketIntelState={candles:Object.fromEntries(['15m','1h','4h','1d'].map(tf=>[tf,rows]))};const a=ctx.coinPrepareAnalysis({ticker:{changePct:1}});assert.equal(a.inds['1h'].volumeRatio,1);assert.equal(a.inds['1h'].last,rows[239].close);assert.notEqual(a.inds['1h'].rsi,ctx.miRSI(rows));});
test('divergence detection uses all returned closed bars and omits the forming bar',()=>{const ctx=context(),now=Date.now();let count;ctx.miRSISeries=rows=>{count=rows.length;return rows.map(()=>50)};ctx.miPivotPoints=()=>[];const rows=Array.from({length:55},(_,i)=>({...candle(i),time:now-(55-i)*300000}));ctx.miDetectDivergence(rows,'5m');assert.equal(count,55);rows.push({...candle(55),time:now});ctx.miDetectDivergence(rows,'5m');assert.equal(count,55);});
