import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../journal.html',import.meta.url),'utf8'),source=readFileSync(new URL('../js/journal-watchtower.js',import.meta.url),'utf8');
const now=1800000000000;
function ctx(){const c=vm.createContext({Date,Math,Number,Map,Set,WORLD_PROTOCOL_SPRITES:{},coinTfMs:{'5m':300000,'15m':900000,'1h':3600000},MI_DIVERGENCE_INTERVALS:['5m','15m','1h'],watchtowerState:{rules:{trendline:true,divergence:true,breakout:true,volume:true,trend:true,elliott:false}},document:{addEventListener(){}},miFmtPrice:n=>String(n),miClamp:(x,a,b)=>Math.max(a,Math.min(b,x)),miAverage:v=>v.reduce((a,b)=>a+b,0)/v.length,coinClosedCandles:(rows,tf,t)=>rows.filter(r=>r.time+({'5m':300000,'15m':900000,'1h':3600000})[tf]<=t)});vm.runInContext(html.slice(html.indexOf('function miEMA('),html.indexOf('function miRenderChart(')),c);vm.runInContext(source,c);c.trendlineDetect=()=>({found:false});c.miDetectDivergence=()=>({found:false});return c;}
function data(){return {symbol:'BTC',receivedAt:now,ticker:{price:110,changePct:2},candles:Object.fromEntries(['5m','15m','1h'].map(tf=>{const step={'5m':300000,'15m':900000,'1h':3600000}[tf];return [tf,Array.from({length:240},(_,i)=>{const p=100+i*.04+Math.sin(i/4);return {time:now-(241-i)*step,open:p-.2,high:p+.8,low:p-.8,close:p,volume:100};})]}))};}
test('forming price and volume spikes do not alter closed-bar watch evidence',()=>{const c=ctx(),d=data(),before=c.watchAnalyze(d,now);for(const rows of Object.values(d.candles))rows.push({time:now,open:110,high:1000,low:100,close:999,volume:100000});const after=c.watchAnalyze(d,now);assert.equal(after.inds['15m'].volumeRatio,1);assert.equal(after.inds['15m'].rsi,before.inds['15m'].rsi);assert.equal(after.inds['1h'].last,before.inds['1h'].last);});
test('overbought RSI stays a warning and cannot flip a bullish background to SHORT',()=>{const c=ctx(),d=data();c.watchtowerState.rules.breakout=false;for(const rows of Object.values(d.candles))rows.forEach((v,i)=>{v.close=100+i;v.open=v.close-.2;v.high=v.close+.8;v.low=v.close-.8;});const r=c.watchAnalyze(d,now);assert.equal(r.direction,'long');assert.equal(r.primary.type,'context');assert.ok(r.warnings.some(w=>w.includes('не сигнал SHORT')));});
test('freshness, extension and actual closed-bar invalidation expire a retest',()=>{const c=ctx();c.trendlineAt=()=>100;const rows=[{time:now-3600000,close:99}],line={all:rows,buffer:.2};let life=c.watchLife({type:'retest',at:now-4*3600000,price:100,direction:'long'},[],'1h',100,2,now);assert.equal(life.expired,true);life=c.watchLife({type:'retest',at:now-1000,price:100,direction:'long'},[],'1h',104,2,now);assert.equal(life.extended,true);life=c.watchLife({type:'retest',at:now-2*3600000,price:100,direction:'long',line},rows,'1h',100,2,now);assert.equal(life.cancelled,true);assert.equal(life.inactive,true);});
test('correlated evidence cannot saturate to 100, conflicts lower priority, inactive scores remain low',()=>{const c=ctx(),input={distance:.1,age:0,tf:'15m',confirmed:true,volume:true,aligned:true,conflicts:0,inactive:false};const score=c.watchPriority(input);assert.ok(score<100);assert.ok(c.watchPriority({...input,conflicts:2})<score);assert.equal(c.watchPriority({...input,inactive:true}),12);assert.ok(c.watchPriority({...input,age:5*900000})<score);});
test('first scan is baseline, number-only changes are silent, new event is recorded once',()=>{const c=ctx(),baseline=new Map(),event={id:'BTC:line',type:'near',stage:'attention',distance:1,at:null,tf:'1h',title:'Линия'};let r={symbol:'BTC',candidates:[event]};assert.equal(c.watchTransitions([r],baseline,now).length,0);r={...r,score:90,candidates:[{...event,distance:.9}]};assert.equal(c.watchTransitions([r],baseline,now+1).length,0);r.candidates=[{...event,type:'break',at:now, title:'Пробой',distance:.3}];assert.equal(c.watchTransitions([r],baseline,now+2).length,1);assert.equal(c.watchTransitions([r],baseline,now+3).length,0);assert.equal(c.watchTransitions([{symbol:'BTC',error:Error('offline')}],baseline,now+4).length,0);assert.equal(c.watchTransitions([r],baseline,now+5).length,0);});
test('cancelled and disappeared observations produce a single archive event',()=>{const c=ctx(),baseline=new Map(),event={id:'BTC:div',type:'divergence',stage:'attention',tf:'5m',at:now,title:'Дивергенция'};c.watchTransitions([{symbol:'BTC',candidates:[event]}],baseline,now);let events=c.watchTransitions([{symbol:'BTC',candidates:[{...event,stage:'inactive'}]}],baseline,now+1);assert.equal(events.length,1);assert.equal(events[0].stage,'inactive');assert.equal(c.watchTransitions([{symbol:'BTC',candidates:[]}],baseline,now+2).length,0);});
test('old observations stay visible alongside the current nearby level',()=>{const c=ctx(),old={id:'old',stage:'inactive',score:12,direction:'long'},current={id:'new',stage:'attention'},r={primary:current,candidates:[current,old],evidence:[{ok:true}]},records=c.watchDisplayRecords([r]);assert.equal(records.length,2);assert.equal(records[1].primary.id,'old');assert.equal(records[1].evidence[0].ok,false);});
test('stale quotes cannot keep a previously confirmed event active',()=>{const c=ctx(),d=data();d.receivedAt=now-181000;const r=c.watchAnalyze(d,now);assert.equal(r.stage,'inactive');assert.equal(r.score,12);assert.equal(r.primary.confirmed,false);assert.ok(r.primary.life.reason.includes('3 минут'));});

test('stale quotes remain inactive even when all observation rules are disabled',()=>{const c=ctx(),d=data();c.watchtowerState.rules={};d.receivedAt=now-181000;const r=c.watchAnalyze(d,now);assert.equal(r.stage,'inactive');assert.equal(r.score,12);assert.equal(r.primary.confirmed,false);});
test('a live quote returning behind the line demotes the retest pending candle closure',()=>{const c=ctx(),d=data();d.ticker.price=99.5;c.trendlineAt=()=>100;c.trendlineDetect=(rows,tf)=>tf!=='15m'?{found:false}:{found:true,all:rows,tf,stateKey:'entry',state:'РЕТЕСТ УДЕРЖАН',side:'resistance',direction:'long',currentLine:100,atr:2,buffer:.2,broken:true,structureBroken:true,retestHeld:true,retestTime:rows.at(-1).time,retestIndex:rows.length-1,breakTime:rows.at(-2).time,breakIndex:rows.length-2,touches:3,anchorOne:{time:rows[20].time},anchorTwo:{time:rows[40].time}};const r=c.watchAnalyze(d,now);assert.equal(r.stage,'attention');assert.equal(r.primary.confirmed,false);assert.equal(r.primary.title,'ЦЕНА ВЕРНУЛАСЬ ЗА ЛИНИЮ');assert.ok(r.primary.wait.includes('закрытие свечи'));});

test('a nearby level without an event has no post-event movement or expiry',()=>{const c=ctx(),life=c.watchLife({type:'near',at:null,price:100},[],'1h',108,2,now);assert.equal(life.move,null);assert.equal(life.inactive,false);});
